# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Sam Hatfield'
tagline:          'A Jekyll theme'
description:      'Oxford DPhil student interested in weather prediction, data assimilation and supercomputing.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
    - jekyll-paginate

# social icons and sharing options
social:
  - icon:	fa fa-twitter
    name:   twitter
    url:	https://twitter.com/s_e_hatfield
    desc:   Follow me on Twitter

  - icon:	fa fa-github
    name:   github
    url:	https://github.com/samhatfield
    desc:	Fork me on github

  - icon: ai ai-researchgate
    name: researchgate
    url: https://www.researchgate.net/profile/Sam_Hatfield
    desc: Check out my Research Gate page

  - icon: ai ai-orcid
    name: orcid
    url: https://orcid.org/0000-0001-7235-6450
    desc: Check out my ORCID page

  - icon: fa fa-linkedin
    name: linkedin
    url:  https://www.linkedin.com/in/hatfieldsam/
    desc: Connect with me on LinkedIn
