# Build settings
highlighter: rouge
description: 'Graduate physicist at Oxford, working on data assimilation and inexact computing'

# Site settings
title: "Sam Hatfield"

email: samhatfield@live.co.uk
logo: "/assets/images/me.jpg"
cover: "/assets/images/clouds.jpg"

name: 'Sam Hatfield'
author: 'Sam Hatfield'
author_image: "/assets/images/me.jpg"

paginate:	5

url: "http://samhatfield.co.uk" # the base hostname & protocol for your site
baseurl: ""
images: "/assets/images/"

# social icons and sharing options
social:
  - icon:	fa fa-twitter
    name:   twitter
    url:	https://twitter.com/s_e_hatfield
    desc:   Follow me on Twitter
    share_url:
    share_title:
    share_link:

  - icon:	fa fa-github
    name:   github
    url:	https://github.com/samhatfield
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: ai ai-researchgate
    name: researchgate
    url: https://www.researchgate.net/profile/Sam_Hatfield 
    desc: Check out my Research Gate page
    share_url:
    share_title:
    share_link: 

  - icon: ai ai-orcid
    name: orcid
    url: https://orcid.org/0000-0001-7235-6450
    desc: Check out my ORCID page
    share_url:
    share_title:
    share_link: 
