# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "samhatfield"
description: > # this means to ignore newlines until "email:"
   Physics | Computers

email: samhatfield@live.co.uk
#blog logo
logo: "/assets/images/sh_logo.png"
# blog cover
cover: "/assets/images/CNV00022.JPG"

name: 'Sam Hatfield'
author: 'Sam Hatfield'
author_image: "/assets/images/me.jpg"

paginate:	5

url: "http://www.samhatfield.co.uk" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/samhatfield
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: flickr
    url: https://www.flickr.com/photos/sam-hatfield/
    desc: Check out my photostream
    share_url:
    share_title:
    share_link: 

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
