# Build settings
highlighter: rouge
description: 'Graduate physicist at Oxford, working on data assimilation and inexact computing'

# Site settings
title: "Sam Hatfield"

email: samhatfield@live.co.uk
logo: "/assets/images/me.jpg"
cover: "/assets/images/clouds.jpg"

name: 'Sam Hatfield'
author: 'Sam Hatfield'
author_image: "/assets/images/me.jpg"

paginate:	5

url: "http://samhatfield.co.uk" # the base hostname & protocol for your site
baseurl: ""
images: "/assets/images/"

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/samhatfield
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: flickr
    url: https://www.flickr.com/photos/sam-hatfield/
    desc: Check out my photostream
    share_url:
    share_title:
    share_link: 

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
